exclude: ['vendor', 'Gemfile', 'Gemfile.lock', 'Readme.md']
markdown: redcarpet
redcarpet:
  extensions: [tables,autolink]
gems:
    - jekyll-sitemap

title: mixi-inc/AndroidTraining

# production env
baseurl: '/AndroidTraining'
components:
    polymer: '/AndroidTraining/components/polymer'

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values: 
            section: ""
            layout: "default"
            description: "AndroidTraining - Training course repository for android app development"
            og_type: "article"
    -
        scope:
            path: "introductions"
            type: "pages"
        values: 
            section: "introductions"
    -
        scope:
            path: "fundamentals"
            type: "pages"
        values: 
            section: "fundamentals"
    -
        scope:
            path: "advanced"
            type: "pages"
        values: 
            section: "advanced"
    -
        scope:
            path: "appendix"
            type: "pages"
        values: 
            section: "appendix"
